### ISSUE TITLE
CI task for publishing

### ISSUE THREAD

**Issue by ashchan** [nervosnetwork/tippy#22]
- [x] CI job for publishing
- [x] Solve `ckb` process fork permission errors on Linux
- [x] Solve `ckb` process fork permission errors on macOS
- [x] [Nice to have] Create `.app` bundle for macOS ([example](https://avaloniaui.net/docs/packing/macOS))
- [x] Create DMG instead of Zip for macOS

```shell
[70658:70672:0107/134000.269716:ERROR:service_utils.cc(157)] --ignore-gpu-blacklist is deprecated and will be removed in 2020Q4, use --ignore-gpu-blocklist instead.
Opening in existing browser session.
Starting child processes...
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM5IPQMARHAN", Request id "0HM5IPQMARHAN:00000003": An unhandled exception was thrown by the application.
      System.ComponentModel.Win32Exception (13): Permission denied
         at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
         at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
         at System.Diagnostics.Process.Start()
         at Tippy.Ctrl.Process.NodeProcess.InitalizeCkbIfNecessary()
         at Tippy.Ctrl.Process.NodeProcess.Configure()
         at Tippy.Ctrl.Process.CommandProcess.Start()
         at Tippy.Ctrl.ProcessGroup.Start()
         at Tippy.Ctrl.ProcessManager.Start(Project project)
         at Tippy.Pages.Projects.StartModel.OnPostAsync(Nullable`1 id)
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by ashchan** [comment]
WIP: https://github.com/nervosnetwork/tippy/pull/23

**Comment by ashchan** [comment]
The error occurs because zip archive doesn't preserve file permissions. We need `ckb`, `ckb-indexer` and `ckb-cli` to have executive permission to be forked by Tippy.

For Linux we can solve this by replacing zipping with gzipping (`tar.gz`). For macOS, we'd consider creating an app bundle, which would still require taking care of the permission issue (and perhaps create a DMG as well).
