### ISSUE TITLE
RPC access error when starting a node for the first time

### ISSUE THREAD

**Issue by ashchan** [nervosnetwork/tippy#39]
When running `Tippy.app` from a DMG for the first time this would happen.

At that time the RPC might not be ready listening yet.

```shell
      Connection id "0HM5P1O79KBSL", Request id "0HM5P1O79KBSL:00000003": An unhandled exception was thrown by the application.
      System.Net.WebException: Connection refused [::ffff:127.0.0.1]:8114 (localhost:8114)
       ---> System.Net.Http.HttpRequestException: Connection refused [::ffff:127.0.0.1]:8114 (localhost:8114)
       ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (61): Connection refused [::ffff:127.0.0.1]:8114
         at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
         at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
         at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
      --- End of stack trace from previous location ---
         at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
         at System.Net.Sockets.Socket.Connect(String host, Int32 port)
         at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
         at System.Net.Http.ConnectHelper.Connect(String host, Int32 port, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.Connect(String host, Int32 port, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
      --- End of stack trace from previous location ---
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.DelegatingHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
         at System.Net.HttpWebRequest.SendRequest(Boolean async)
         at System.Net.HttpWebRequest.GetResponse()
         --- End of inner exception stack trace ---
         at System.Net.HttpWebRequest.GetResponse()
         at Ckb.Rpc.BaseClient.Call[T](String method, Object[] methodParams) in /Users/runner/work/tippy/tippy/src/Ckb.Rpc/BaseClient.cs:line 38
         at Ckb.Rpc.Client.GetCurrentEpoch() in /Users/runner/work/tippy/tippy/src/Ckb.Rpc/Client.cs:line 47
         at Tippy.Pages.PageModelBase.OnPageHandlerExecutionAsync(PageHandlerExecutingContext context, PageHandlerExecutionDelegate next) in /Users/runner/work/tippy/tippy/src/Tippy/Pages/PageModelBase.cs:line 51
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
```

**Comment by ashchan** [comment]
Handle the exception silently. https://github.com/nervosnetwork/tippy/commit/d0e77dfa20f30386362938527e1227ecf84c1ee7, https://github.com/nervosnetwork/tippy/commit/b21bf4135f223537aed8bfd8d11cf0b719bcb7e0.
